# Generated by NeuroStack
# Artifact: workflow/sample_test_100

"""
Workflow: sample_test_100
Description: does route to writer agent to write 
Instructions: does route to writer agent to write 
"""
from __future__ import annotations
from google.adk import Agent
from google.adk.tools import load_memory
from google.genai import types

import importlib.util as _ilu
import pathlib as _pl
_spec_agents_writer_agent = _ilu.spec_from_file_location(
    'writer_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'writer_agent' / 'agent.py',
)
_mod_agents_writer_agent = _ilu.module_from_spec(_spec_agents_writer_agent)
_spec_agents_writer_agent.loader.exec_module(_mod_agents_writer_agent)

writer_agent = _mod_agents_writer_agent.root_agent





root_agent = Agent(
    model='us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    name="sample_test_100",
    description="""does route to writer agent to write """,
    instruction="""does route to writer agent to write """,
    global_instruction="""does route to writer agent to write """,
    sub_agents=[writer_agent],
    generate_content_config=types.GenerateContentConfig(
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
    tools=[load_memory],
)
