# Generated by NeuroStack
# Artifact: agent/testing_agent_1000

"""
System prompt for testing_agent_1000.
"""

AGENT_DESCRIPTION = """
convert the language into another according to the prompt
"""

SYSTEM_PROMPT = """
convert the language into another according to the prompt

the language conversion will be from english to french
"""
