# Generated by NeuroStack
# Artifact: workflow/tier3_panel_report_100

"""
Workflow: tier3_panel_report_100
Description: Writes a short report and has it reviewed
Instructions: Write a short report on the topic, then zip the final report and send it to the archive team.
"""
from __future__ import annotations
from google.adk import Agent
from google.genai import types

import importlib.util as _ilu
import pathlib as _pl
_spec_agents_critic_agent = _ilu.spec_from_file_location(
    'critic_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'critic_agent' / 'agent.py',
)
_mod_agents_critic_agent = _ilu.module_from_spec(_spec_agents_critic_agent)
_spec_agents_critic_agent.loader.exec_module(_mod_agents_critic_agent)
_spec_agents_writer_agent = _ilu.spec_from_file_location(
    'writer_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'writer_agent' / 'agent.py',
)
_mod_agents_writer_agent = _ilu.module_from_spec(_spec_agents_writer_agent)
_spec_agents_writer_agent.loader.exec_module(_mod_agents_writer_agent)

writer_agent = _mod_agents_writer_agent.root_agent
critic_agent = _mod_agents_critic_agent.root_agent





root_agent = Agent(
    model='gemini/gemini-2.5-pro',
    name="tier3_panel_report_100",
    description="""Writes a short report and has it reviewed""",
    instruction="""Write a short report on the topic, then zip the final report and send it to the archive team.""",
    global_instruction="""Write a short report on the topic, then zip the final report and send it to the archive team.""",
    sub_agents=[writer_agent, critic_agent],
    generate_content_config=types.GenerateContentConfig(
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
    tools=[],
)
