# Generated by NeuroStack
# Vendored from platform origin: tool/financial_plotting_tools (upstream_version=platform)

"""
Financial Plotting & Analysis Tools - financial_plotting_tools.py

Advanced plotting and analysis tools specifically designed for financial data visualization
and trend analysis. This module provides comprehensive charting capabilities using both
matplotlib and plotly for static and interactive visualizations.

Generated on: 2025-01-15
Total tools: 8
"""

from typing import Dict, Any, List, Optional, Union
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
import io
import base64
import datetime
import json
from pathlib import Path
import os


def create_stock_line_chart(
    stock_data: List[Dict[str, Any]],
    ticker: str,
    price_column: str = "close",
    title: Optional[str] = None,
    output_path: Optional[str] = None,
    include_volume: bool = False
) -> Dict[str, Any]:
    """
    Create a time series line chart for stock price data.
    
    Args:
        stock_data (List[Dict]): List of stock data dictionaries with date and price info
        ticker (str): Stock ticker symbol for labeling
        price_column (str): Column to plot ('close', 'open', 'high', 'low', 'adj_close')
        title (str): Custom title for the chart
        output_path (str): Path to save the chart image
        include_volume (bool): Include volume subplot
        
    Returns:
        Dict[str, Any]: Chart creation results with base64 encoded image
    """
    try:
        if not stock_data or not isinstance(stock_data, list):
            return {
                "success": False,
                "message": "Invalid stock data provided",
                "data": None
            }
        
        # Convert to DataFrame
        df = pd.DataFrame(stock_data)
        
        # Ensure date column is datetime
        if 'Date' in df.columns:
            df['Date'] = pd.to_datetime(df['Date'])
        elif 'date' in df.columns:
            df['Date'] = pd.to_datetime(df['date'])
        else:
            return {
                "success": False,
                "message": "No date column found in data",
                "data": None
            }
        
        # Sort by date
        df = df.sort_values('Date')
        
        # Check if price column exists
        available_columns = [col.lower() for col in df.columns]
        if price_column.lower() not in available_columns:
            return {
                "success": False,
                "message": f"Column '{price_column}' not found in data",
                "data": None
            }
        
        # Find the actual column name (case-insensitive)
        actual_column = next(col for col in df.columns if col.lower() == price_column.lower())
        
        # Create subplot configuration
        if include_volume:
            fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), height_ratios=[3, 1])
        else:
            fig, ax1 = plt.subplots(figsize=(12, 6))
        
        # Plot price data
        ax1.plot(df['Date'], df[actual_column], linewidth=2, label=f'{ticker} {price_column.title()}')
        
        # Customize price chart
        ax1.set_ylabel(f'{price_column.title()} Price ($)')
        ax1.set_title(title or f'{ticker} {price_column.title()} Price Over Time')
        ax1.grid(True, alpha=0.3)
        ax1.legend()
        
        # Format x-axis
        ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
        ax1.xaxis.set_major_locator(mdates.MonthLocator())
        plt.setp(ax1.xaxis.get_majorticklabels(), rotation=45)
        
        # Add volume subplot if requested
        if include_volume:
            volume_column = next((col for col in df.columns if col.lower() == 'volume'), None)
            if volume_column:
                ax2.bar(df['Date'], df[volume_column], alpha=0.7, color='orange')
                ax2.set_ylabel('Volume')
                ax2.set_xlabel('Date')
                ax2.grid(True, alpha=0.3)
                plt.setp(ax2.xaxis.get_majorticklabels(), rotation=45)
        
        plt.tight_layout()
        
        # Save or convert to base64
        if output_path:
            plt.savefig(output_path, dpi=300, bbox_inches='tight')
            plt.close()
            
            return {
                "success": True,
                "message": f"Stock line chart saved to {output_path}",
                "data": {
                    "ticker": ticker,
                    "output_path": output_path,
                    "chart_type": "line",
                    "data_points": len(df),
                    "date_range": {
                        "start": df['Date'].min().strftime('%Y-%m-%d'),
                        "end": df['Date'].max().strftime('%Y-%m-%d')
                    }
                }
            }
        else:
            # Convert to base64
            buffer = io.BytesIO()
            plt.savefig(buffer, format='png', dpi=300, bbox_inches='tight')
            buffer.seek(0)
            img_base64 = base64.b64encode(buffer.read()).decode()
            plt.close()
            
            return {
                "success": True,
                "message": f"Stock line chart created for {ticker}",
                "data": {
                    "ticker": ticker,
                    "image_base64": img_base64,
                    "chart_type": "line",
                    "data_points": len(df),
                    "date_range": {
                        "start": df['Date'].min().strftime('%Y-%m-%d'),
                        "end": df['Date'].max().strftime('%Y-%m-%d')
                    }
                }
            }
        
    except Exception as e:
        return {
            "success": False,
            "message": f"Error creating stock line chart: {str(e)}",
            "data": None
        }


def create_candlestick_chart(
    stock_data: List[Dict[str, Any]],
    ticker: str,
    title: Optional[str] = None,
    output_path: Optional[str] = None,
    include_volume: bool = True
) -> Dict[str, Any]:
    """
    Create an interactive candlestick chart using Plotly.
    
    Args:
        stock_data (List[Dict]): List of stock data with OHLC data
        ticker (str): Stock ticker symbol
        title (str): Custom title for the chart
        output_path (str): Path to save the HTML file
        include_volume (bool): Include volume subplot
        
    Returns:
        Dict[str, Any]: Chart creation results with HTML content
    """
    try:
        if not stock_data or not isinstance(stock_data, list):
            return {
                "success": False,
                "message": "Invalid stock data provided",
                "data": None
            }
        
        # Convert to DataFrame
        df = pd.DataFrame(stock_data)
        
        # Ensure date column is datetime
        if 'Date' in df.columns:
            df['Date'] = pd.to_datetime(df['Date'])
        elif 'date' in df.columns:
            df['Date'] = pd.to_datetime(df['date'])
        else:
            return {
                "success": False,
                "message": "No date column found in data",
                "data": None
            }
        
        # Sort by date
        df = df.sort_values('Date')
        
        # Check required columns
        required_columns = ['open', 'high', 'low', 'close']
        available_columns = [col.lower() for col in df.columns]
        
        column_mapping = {}
        for req_col in required_columns:
            actual_col = next((col for col in df.columns if col.lower() == req_col), None)
            if not actual_col:
                return {
                    "success": False,
                    "message": f"Required column '{req_col}' not found in data",
                    "data": None
                }
            column_mapping[req_col] = actual_col
        
        # Create subplot configuration
        if include_volume:
            fig = make_subplots(
                rows=2, cols=1,
                shared_xaxes=True,
                vertical_spacing=0.1,
                subplot_titles=(f'{ticker} Price', 'Volume'),
                row_heights=[0.7, 0.3]
            )
        else:
            fig = make_subplots(rows=1, cols=1)
        
        # Add candlestick chart
        fig.add_trace(
            go.Candlestick(
                x=df['Date'],
                open=df[column_mapping['open']],
                high=df[column_mapping['high']],
                low=df[column_mapping['low']],
                close=df[column_mapping['close']],
                name=ticker,
                increasing_line_color='green',
                decreasing_line_color='red'
            ),
            row=1, col=1
        )
        
        # Add volume if requested
        if include_volume:
            volume_column = next((col for col in df.columns if col.lower() == 'volume'), None)
            if volume_column:
                fig.add_trace(
                    go.Bar(
                        x=df['Date'],
                        y=df[volume_column],
                        name='Volume',
                        marker_color='orange',
                        opacity=0.7
                    ),
                    row=2, col=1
                )
        
        # Update layout
        fig.update_layout(
            title=title or f'{ticker} Candlestick Chart',
            yaxis_title='Price ($)',
            xaxis_title='Date',
            xaxis_rangeslider_visible=False,
            height=600 if include_volume else 400,
            showlegend=True
        )
        
        # Save or return HTML
        if output_path:
            fig.write_html(output_path)
            
            return {
                "success": True,
                "message": f"Candlestick chart saved to {output_path}",
                "data": {
                    "ticker": ticker,
                    "output_path": output_path,
                    "chart_type": "candlestick",
                    "data_points": len(df),
                    "date_range": {
                        "start": df['Date'].min().strftime('%Y-%m-%d'),
                        "end": df['Date'].max().strftime('%Y-%m-%d')
                    }
                }
            }
        else:
            html_content = fig.to_html(include_plotlyjs='cdn')
            
            return {
                "success": True,
                "message": f"Candlestick chart created for {ticker}",
                "data": {
                    "ticker": ticker,
                    "html_content": html_content,
                    "chart_type": "candlestick",
                    "data_points": len(df),
                    "date_range": {
                        "start": df['Date'].min().strftime('%Y-%m-%d'),
                        "end": df['Date'].max().strftime('%Y-%m-%d')
                    }
                }
            }
        
    except Exception as e:
        return {
            "success": False,
            "message": f"Error creating candlestick chart: {str(e)}",
            "data": None
        }


def create_volume_chart(
    stock_data: List[Dict[str, Any]],
    ticker: str,
    chart_type: str = "bar",
    title: Optional[str] = None,
    output_path: Optional[str] = None
) -> Dict[str, Any]:
    """
    Create a volume analysis chart.
    
    Args:
        stock_data (List[Dict]): List of stock data with volume information
        ticker (str): Stock ticker symbol
        chart_type (str): Type of chart ('bar', 'line', 'area')
        title (str): Custom title for the chart
        output_path (str): Path to save the chart image
        
    Returns:
        Dict[str, Any]: Chart creation results
    """
    try:
        if not stock_data or not isinstance(stock_data, list):
            return {
                "success": False,
                "message": "Invalid stock data provided",
                "data": None
            }
        
        # Convert to DataFrame
        df = pd.DataFrame(stock_data)
        
        # Ensure date column is datetime
        if 'Date' in df.columns:
            df['Date'] = pd.to_datetime(df['Date'])
        elif 'date' in df.columns:
            df['Date'] = pd.to_datetime(df['date'])
        else:
            return {
                "success": False,
                "message": "No date column found in data",
                "data": None
            }
        
        # Find volume column
        volume_column = next((col for col in df.columns if col.lower() == 'volume'), None)
        if not volume_column:
            return {
                "success": False,
                "message": "Volume column not found in data",
                "data": None
            }
        
        # Sort by date
        df = df.sort_values('Date')
        
        # Create chart
        fig, ax = plt.subplots(figsize=(12, 6))
        
        if chart_type == "bar":
            ax.bar(df['Date'], df[volume_column], alpha=0.7, color='orange')
        elif chart_type == "line":
            ax.plot(df['Date'], df[volume_column], linewidth=2, color='orange')
        elif chart_type == "area":
            ax.fill_between(df['Date'], df[volume_column], alpha=0.7, color='orange')
        
        # Customize chart
        ax.set_ylabel('Volume')
        ax.set_xlabel('Date')
        ax.set_title(title or f'{ticker} Volume Analysis')
        ax.grid(True, alpha=0.3)
        
        # Format x-axis
        ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
        ax.xaxis.set_major_locator(mdates.MonthLocator())
        plt.setp(ax.xaxis.get_majorticklabels(), rotation=45)
        
        plt.tight_layout()
        
        # Calculate volume statistics
        volume_stats = {
            "average_volume": df[volume_column].mean(),
            "max_volume": df[volume_column].max(),
            "min_volume": df[volume_column].min(),
            "total_volume": df[volume_column].sum()
        }
        
        # Save or convert to base64
        if output_path:
            plt.savefig(output_path, dpi=300, bbox_inches='tight')
            plt.close()
            
            return {
                "success": True,
                "message": f"Volume chart saved to {output_path}",
                "data": {
                    "ticker": ticker,
                    "output_path": output_path,
                    "chart_type": f"volume_{chart_type}",
                    "volume_statistics": volume_stats,
                    "data_points": len(df)
                }
            }
        else:
            # Convert to base64
            buffer = io.BytesIO()
            plt.savefig(buffer, format='png', dpi=300, bbox_inches='tight')
            buffer.seek(0)
            img_base64 = base64.b64encode(buffer.read()).decode()
            plt.close()
            
            return {
                "success": True,
                "message": f"Volume chart created for {ticker}",
                "data": {
                    "ticker": ticker,
                    "image_base64": img_base64,
                    "chart_type": f"volume_{chart_type}",
                    "volume_statistics": volume_stats,
                    "data_points": len(df)
                }
            }
        
    except Exception as e:
        return {
            "success": False,
            "message": f"Error creating volume chart: {str(e)}",
            "data": None
        }


def create_comparison_chart(
    stock_data_dict: Dict[str, List[Dict[str, Any]]],
    price_column: str = "close",
    normalize: bool = False,
    title: Optional[str] = None,
    output_path: Optional[str] = None
) -> Dict[str, Any]:
    """
    Create a comparison chart for multiple stocks.
    
    Args:
        stock_data_dict (Dict): Dictionary with ticker as key and stock data as value
        price_column (str): Column to plot for comparison
        normalize (bool): Normalize prices to percentage change from start
        title (str): Custom title for the chart
        output_path (str): Path to save the chart image
        
    Returns:
        Dict[str, Any]: Chart creation results
    """
    try:
        if not stock_data_dict or not isinstance(stock_data_dict, dict):
            return {
                "success": False,
                "message": "Invalid stock data dictionary provided",
                "data": None
            }
        
        fig, ax = plt.subplots(figsize=(12, 8))
        
        colors = ['blue', 'red', 'green', 'orange', 'purple', 'brown', 'pink', 'gray']
        ticker_stats = {}
        
        for i, (ticker, data) in enumerate(stock_data_dict.items()):
            # Convert to DataFrame
            df = pd.DataFrame(data)
            
            # Ensure date column is datetime
            if 'Date' in df.columns:
                df['Date'] = pd.to_datetime(df['Date'])
            elif 'date' in df.columns:
                df['Date'] = pd.to_datetime(df['date'])
            else:
                continue
            
            # Sort by date
            df = df.sort_values('Date')
            
            # Find price column
            actual_column = next((col for col in df.columns if col.lower() == price_column.lower()), None)
            if not actual_column:
                continue
            
            # Get price data
            prices = df[actual_column]
            
            # Normalize if requested
            if normalize:
                prices = (prices / prices.iloc[0] - 1) * 100
                ylabel = 'Percentage Change (%)'
            else:
                ylabel = f'{price_column.title()} Price ($)'
            
            # Plot
            color = colors[i % len(colors)]
            ax.plot(df['Date'], prices, linewidth=2, label=ticker, color=color)
            
            # Calculate statistics
            ticker_stats[ticker] = {
                "start_price": df[actual_column].iloc[0],
                "end_price": df[actual_column].iloc[-1],
                "change": df[actual_column].iloc[-1] - df[actual_column].iloc[0],
                "change_percent": ((df[actual_column].iloc[-1] / df[actual_column].iloc[0]) - 1) * 100,
                "max_price": df[actual_column].max(),
                "min_price": df[actual_column].min(),
                "volatility": df[actual_column].std()
            }
        
        # Customize chart
        ax.set_ylabel(ylabel)
        ax.set_xlabel('Date')
        ax.set_title(title or f'Stock Comparison - {price_column.title()} Price')
        ax.grid(True, alpha=0.3)
        ax.legend()
        
        # Format x-axis
        ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
        ax.xaxis.set_major_locator(mdates.MonthLocator())
        plt.setp(ax.xaxis.get_majorticklabels(), rotation=45)
        
        plt.tight_layout()
        
        # Save or convert to base64
        if output_path:
            plt.savefig(output_path, dpi=300, bbox_inches='tight')
            plt.close()
            
            return {
                "success": True,
                "message": f"Comparison chart saved to {output_path}",
                "data": {
                    "output_path": output_path,
                    "chart_type": "comparison",
                    "tickers": list(stock_data_dict.keys()),
                    "normalized": normalize,
                    "ticker_statistics": ticker_stats
                }
            }
        else:
            # Convert to base64
            buffer = io.BytesIO()
            plt.savefig(buffer, format='png', dpi=300, bbox_inches='tight')
            buffer.seek(0)
            img_base64 = base64.b64encode(buffer.read()).decode()
            plt.close()
            
            return {
                "success": True,
                "message": f"Comparison chart created for {len(stock_data_dict)} stocks",
                "data": {
                    "image_base64": img_base64,
                    "chart_type": "comparison",
                    "tickers": list(stock_data_dict.keys()),
                    "normalized": normalize,
                    "ticker_statistics": ticker_stats
                }
            }
        
    except Exception as e:
        return {
            "success": False,
            "message": f"Error creating comparison chart: {str(e)}",
            "data": None
        }


def create_technical_indicators_chart(
    stock_data: List[Dict[str, Any]],
    ticker: str,
    indicators: Optional[List[str]] = None,
    title: Optional[str] = None,
    output_path: Optional[str] = None
) -> Dict[str, Any]:
    """
    Create a chart with technical indicators.
    
    Args:
        stock_data (List[Dict]): List of stock data
        ticker (str): Stock ticker symbol
        indicators (List[str]): List of indicators to include ('sma_20', 'sma_50', 'rsi', 'bollinger')
        title (str): Custom title for the chart
        output_path (str): Path to save the chart image
        
    Returns:
        Dict[str, Any]: Chart creation results with technical analysis
    """
    try:
        if not stock_data or not isinstance(stock_data, list):
            return {
                "success": False,
                "message": "Invalid stock data provided",
                "data": None
            }
        
        if indicators is None:
            indicators = ['sma_20', 'sma_50']
        
        # Convert to DataFrame
        df = pd.DataFrame(stock_data)
        
        # Ensure date column is datetime
        if 'Date' in df.columns:
            df['Date'] = pd.to_datetime(df['Date'])
        elif 'date' in df.columns:
            df['Date'] = pd.to_datetime(df['date'])
        else:
            return {
                "success": False,
                "message": "No date column found in data",
                "data": None
            }
        
        # Sort by date
        df = df.sort_values('Date')
        
        # Find price column
        close_column = next((col for col in df.columns if col.lower() == 'close'), None)
        if not close_column:
            return {
                "success": False,
                "message": "Close price column not found in data",
                "data": None
            }
        
        # Calculate technical indicators
        technical_data = {}
        
        if 'sma_20' in indicators:
            df['SMA_20'] = df[close_column].rolling(window=20).mean()
            technical_data['sma_20'] = df['SMA_20'].dropna().tolist()
        
        if 'sma_50' in indicators:
            df['SMA_50'] = df[close_column].rolling(window=50).mean()
            technical_data['sma_50'] = df['SMA_50'].dropna().tolist()
        
        if 'rsi' in indicators:
            # Simple RSI calculation
            delta = df[close_column].diff()
            gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
            loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
            rs = gain / loss
            df['RSI'] = 100 - (100 / (1 + rs))
            technical_data['rsi'] = df['RSI'].dropna().tolist()
        
        if 'bollinger' in indicators:
            # Bollinger Bands
            sma_20 = df[close_column].rolling(window=20).mean()
            std_20 = df[close_column].rolling(window=20).std()
            df['BB_Upper'] = sma_20 + (std_20 * 2)
            df['BB_Lower'] = sma_20 - (std_20 * 2)
            technical_data['bollinger_upper'] = df['BB_Upper'].dropna().tolist()
            technical_data['bollinger_lower'] = df['BB_Lower'].dropna().tolist()
        
        # Create subplots
        if 'rsi' in indicators:
            fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 10), height_ratios=[3, 1])
        else:
            fig, ax1 = plt.subplots(figsize=(12, 8))
        
        # Plot price and moving averages
        ax1.plot(df['Date'], df[close_column], linewidth=2, label=f'{ticker} Close', color='blue')
        
        if 'sma_20' in indicators:
            ax1.plot(df['Date'], df['SMA_20'], linewidth=1, label='SMA 20', color='red', alpha=0.7)
        
        if 'sma_50' in indicators:
            ax1.plot(df['Date'], df['SMA_50'], linewidth=1, label='SMA 50', color='green', alpha=0.7)
        
        if 'bollinger' in indicators:
            ax1.plot(df['Date'], df['BB_Upper'], linewidth=1, label='Bollinger Upper', color='orange', alpha=0.7)
            ax1.plot(df['Date'], df['BB_Lower'], linewidth=1, label='Bollinger Lower', color='orange', alpha=0.7)
            ax1.fill_between(df['Date'], df['BB_Upper'], df['BB_Lower'], alpha=0.1, color='orange')
        
        ax1.set_ylabel('Price ($)')
        ax1.set_title(title or f'{ticker} Technical Analysis')
        ax1.grid(True, alpha=0.3)
        ax1.legend()
        
        # Plot RSI if requested
        if 'rsi' in indicators:
            ax2.plot(df['Date'], df['RSI'], linewidth=2, color='purple')
            ax2.axhline(y=70, color='r', linestyle='--', alpha=0.7)
            ax2.axhline(y=30, color='g', linestyle='--', alpha=0.7)
            ax2.set_ylabel('RSI')
            ax2.set_xlabel('Date')
            ax2.set_ylim(0, 100)
            ax2.grid(True, alpha=0.3)
        
        # Format x-axis
        ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
        ax1.xaxis.set_major_locator(mdates.MonthLocator())
        plt.setp(ax1.xaxis.get_majorticklabels(), rotation=45)
        
        plt.tight_layout()
        
        # Save or convert to base64
        if output_path:
            plt.savefig(output_path, dpi=300, bbox_inches='tight')
            plt.close()
            
            return {
                "success": True,
                "message": f"Technical indicators chart saved to {output_path}",
                "data": {
                    "ticker": ticker,
                    "output_path": output_path,
                    "chart_type": "technical_indicators",
                    "indicators": indicators,
                    "technical_data": technical_data,
                    "data_points": len(df)
                }
            }
        else:
            # Convert to base64
            buffer = io.BytesIO()
            plt.savefig(buffer, format='png', dpi=300, bbox_inches='tight')
            buffer.seek(0)
            img_base64 = base64.b64encode(buffer.read()).decode()
            plt.close()
            
            return {
                "success": True,
                "message": f"Technical indicators chart created for {ticker}",
                "data": {
                    "ticker": ticker,
                    "image_base64": img_base64,
                    "chart_type": "technical_indicators",
                    "indicators": indicators,
                    "technical_data": technical_data,
                    "data_points": len(df)
                }
            }
        
    except Exception as e:
        return {
            "success": False,
            "message": f"Error creating technical indicators chart: {str(e)}",
            "data": None
        }


def analyze_stock_trends(
    stock_data: List[Dict[str, Any]],
    ticker: str,
    analysis_period: int = 30
) -> Dict[str, Any]:
    """
    Analyze stock trends and generate text insights.
    
    Args:
        stock_data (List[Dict]): List of stock data
        ticker (str): Stock ticker symbol
        analysis_period (int): Number of days to analyze for trends
        
    Returns:
        Dict[str, Any]: Trend analysis results with insights
    """
    try:
        if not stock_data or not isinstance(stock_data, list):
            return {
                "success": False,
                "message": "Invalid stock data provided",
                "data": None
            }
        
        # Convert to DataFrame
        df = pd.DataFrame(stock_data)
        
        # Ensure date column is datetime
        if 'Date' in df.columns:
            df['Date'] = pd.to_datetime(df['Date'])
        elif 'date' in df.columns:
            df['Date'] = pd.to_datetime(df['date'])
        else:
            return {
                "success": False,
                "message": "No date column found in data",
                "data": None
            }
        
        # Sort by date
        df = df.sort_values('Date')
        
        # Find price column
        close_column = next((col for col in df.columns if col.lower() == 'close'), None)
        if not close_column:
            return {
                "success": False,
                "message": "Close price column not found in data",
                "data": None
            }
        
        # Calculate trend metrics
        recent_data = df.tail(min(analysis_period, len(df)))
        
        # Price changes
        total_change = recent_data[close_column].iloc[-1] - recent_data[close_column].iloc[0]
        total_change_percent = (total_change / recent_data[close_column].iloc[0]) * 100
        
        # Daily returns
        df['Daily_Return'] = df[close_column].pct_change()
        recent_returns = df.tail(analysis_period)['Daily_Return'].dropna()
        
        # Volatility
        volatility = recent_returns.std() * np.sqrt(252)  # Annualized volatility
        
        # Trend direction
        if total_change_percent > 5:
            trend_direction = "Strong Upward"
        elif total_change_percent > 1:
            trend_direction = "Upward"
        elif total_change_percent < -5:
            trend_direction = "Strong Downward"
        elif total_change_percent < -1:
            trend_direction = "Downward"
        else:
            trend_direction = "Sideways"
        
        # Support and resistance levels
        recent_highs = recent_data[close_column].rolling(window=5).max()
        recent_lows = recent_data[close_column].rolling(window=5).min()
        
        resistance_level = recent_highs.max()
        support_level = recent_lows.min()
        
        # Generate insights
        insights = []
        
        # Trend insight
        insights.append(f"Over the past {analysis_period} days, {ticker} has shown a {trend_direction.lower()} trend with a {total_change_percent:.2f}% change.")
        
        # Volatility insight
        if volatility > 0.3:
            insights.append(f"The stock exhibits high volatility with an annualized volatility of {volatility:.2f}%.")
        elif volatility < 0.15:
            insights.append(f"The stock shows low volatility with an annualized volatility of {volatility:.2f}%.")
        else:
            insights.append(f"The stock demonstrates moderate volatility with an annualized volatility of {volatility:.2f}%.")
        
        # Price levels insight
        current_price = recent_data[close_column].iloc[-1]
        insights.append(f"Current price of ${current_price:.2f} is trading between support level of ${support_level:.2f} and resistance level of ${resistance_level:.2f}.")
        
        # Recent performance
        recent_performance = recent_returns.tail(5).mean() * 100
        if recent_performance > 1:
            insights.append(f"Recent performance shows strong momentum with average daily returns of {recent_performance:.2f}%.")
        elif recent_performance < -1:
            insights.append(f"Recent performance shows weakness with average daily returns of {recent_performance:.2f}%.")
        else:
            insights.append(f"Recent performance shows consolidation with average daily returns of {recent_performance:.2f}%.")
        
        # Compile analysis data
        analysis_data = {
            "ticker": ticker,
            "analysis_period": analysis_period,
            "price_metrics": {
                "current_price": current_price,
                "period_start_price": recent_data[close_column].iloc[0],
                "period_end_price": recent_data[close_column].iloc[-1],
                "total_change": total_change,
                "total_change_percent": total_change_percent,
                "highest_price": recent_data[close_column].max(),
                "lowest_price": recent_data[close_column].min()
            },
            "volatility_metrics": {
                "daily_volatility": recent_returns.std(),
                "annualized_volatility": volatility,
                "average_daily_return": recent_returns.mean(),
                "max_daily_gain": recent_returns.max(),
                "max_daily_loss": recent_returns.min()
            },
            "trend_analysis": {
                "direction": trend_direction,
                "support_level": support_level,
                "resistance_level": resistance_level,
                "trend_strength": abs(total_change_percent)
            },
            "insights": insights,
            "summary": f"{ticker} is currently in a {trend_direction.lower()} trend with {volatility:.1%} annualized volatility. The stock has {'' if total_change_percent > 0 else 'de'}clined {abs(total_change_percent):.2f}% over the past {analysis_period} days."
        }
        
        return {
            "success": True,
            "message": f"Stock trend analysis completed for {ticker}",
            "data": analysis_data
        }
        
    except Exception as e:
        return {
            "success": False,
            "message": f"Error analyzing stock trends: {str(e)}",
            "data": None
        }


def calculate_volatility_metrics(
    stock_data: List[Dict[str, Any]],
    ticker: str,
    window_size: int = 20
) -> Dict[str, Any]:
    """
    Calculate comprehensive volatility metrics for stock analysis.
    
    Args:
        stock_data (List[Dict]): List of stock data
        ticker (str): Stock ticker symbol
        window_size (int): Rolling window size for calculations
        
    Returns:
        Dict[str, Any]: Volatility metrics and analysis
    """
    try:
        if not stock_data or not isinstance(stock_data, list):
            return {
                "success": False,
                "message": "Invalid stock data provided",
                "data": None
            }
        
        # Convert to DataFrame
        df = pd.DataFrame(stock_data)
        
        # Ensure date column is datetime
        if 'Date' in df.columns:
            df['Date'] = pd.to_datetime(df['Date'])
        elif 'date' in df.columns:
            df['Date'] = pd.to_datetime(df['date'])
        else:
            return {
                "success": False,
                "message": "No date column found in data",
                "data": None
            }
        
        # Sort by date
        df = df.sort_values('Date')
        
        # Find price columns
        close_column = next((col for col in df.columns if col.lower() == 'close'), None)
        high_column = next((col for col in df.columns if col.lower() == 'high'), None)
        low_column = next((col for col in df.columns if col.lower() == 'low'), None)
        
        if not close_column:
            return {
                "success": False,
                "message": "Close price column not found in data",
                "data": None
            }
        
        # Calculate returns
        df['Daily_Return'] = df[close_column].pct_change()
        df['Log_Return'] = np.log(df[close_column] / df[close_column].shift(1))
        
        # Rolling volatility
        df['Rolling_Volatility'] = df['Daily_Return'].rolling(window=window_size).std()
        df['Rolling_Volatility_Annualized'] = df['Rolling_Volatility'] * np.sqrt(252)
        
        # True Range (if high/low data available)
        if high_column and low_column:
            df['True_Range'] = np.maximum(
                df[high_column] - df[low_column],
                np.maximum(
                    abs(df[high_column] - df[close_column].shift(1)),
                    abs(df[low_column] - df[close_column].shift(1))
                )
            )
            df['Average_True_Range'] = df['True_Range'].rolling(window=window_size).mean()
        
        # Calculate comprehensive metrics
        returns = df['Daily_Return'].dropna()
        
        volatility_metrics = {
            "ticker": ticker,
            "data_period": {
                "start_date": df['Date'].min().strftime('%Y-%m-%d'),
                "end_date": df['Date'].max().strftime('%Y-%m-%d'),
                "total_days": len(df),
                "trading_days": len(returns)
            },
            "basic_volatility": {
                "daily_volatility": returns.std(),
                "annualized_volatility": returns.std() * np.sqrt(252),
                "monthly_volatility": returns.std() * np.sqrt(21),
                "weekly_volatility": returns.std() * np.sqrt(5)
            },
            "return_metrics": {
                "mean_daily_return": returns.mean(),
                "median_daily_return": returns.median(),
                "max_daily_return": returns.max(),
                "min_daily_return": returns.min(),
                "skewness": returns.skew(),
                "kurtosis": returns.kurtosis()
            },
            "risk_metrics": {
                "value_at_risk_95": returns.quantile(0.05),
                "value_at_risk_99": returns.quantile(0.01),
                "sharpe_ratio": (returns.mean() / returns.std()) * np.sqrt(252) if returns.std() != 0 else 0,
                "maximum_drawdown": _calculate_max_drawdown(df[close_column])
            },
            "rolling_metrics": {
                "current_volatility": df['Rolling_Volatility_Annualized'].iloc[-1] if not df['Rolling_Volatility_Annualized'].empty else None,
                "max_volatility": df['Rolling_Volatility_Annualized'].max(),
                "min_volatility": df['Rolling_Volatility_Annualized'].min(),
                "avg_volatility": df['Rolling_Volatility_Annualized'].mean()
            }
        }
        
        # Add ATR metrics if available
        if 'Average_True_Range' in df.columns:
            volatility_metrics["atr_metrics"] = {
                "current_atr": df['Average_True_Range'].iloc[-1],
                "max_atr": df['Average_True_Range'].max(),
                "min_atr": df['Average_True_Range'].min(),
                "avg_atr": df['Average_True_Range'].mean()
            }
        
        # Volatility classification
        annualized_vol = returns.std() * np.sqrt(252)
        if annualized_vol > 0.4:
            vol_classification = "Very High"
        elif annualized_vol > 0.25:
            vol_classification = "High"
        elif annualized_vol > 0.15:
            vol_classification = "Moderate"
        elif annualized_vol > 0.1:
            vol_classification = "Low"
        else:
            vol_classification = "Very Low"
        
        volatility_metrics["volatility_classification"] = vol_classification
        
        # Generate insights
        insights = []
        insights.append(f"{ticker} exhibits {vol_classification.lower()} volatility with an annualized volatility of {annualized_vol:.2%}.")
        
        if volatility_metrics["risk_metrics"]["sharpe_ratio"] > 1:
            insights.append("The stock shows good risk-adjusted returns with a Sharpe ratio above 1.0.")
        elif volatility_metrics["risk_metrics"]["sharpe_ratio"] < 0:
            insights.append("The stock shows poor risk-adjusted returns with a negative Sharpe ratio.")
        
        volatility_metrics["insights"] = insights
        
        return {
            "success": True,
            "message": f"Volatility metrics calculated for {ticker}",
            "data": volatility_metrics
        }
        
    except Exception as e:
        return {
            "success": False,
            "message": f"Error calculating volatility metrics: {str(e)}",
            "data": None
        }


def generate_financial_summary(
    stock_data: List[Dict[str, Any]],
    ticker: str,
    include_recommendations: bool = True
) -> Dict[str, Any]:
    """
    Generate a comprehensive financial summary report.
    
    Args:
        stock_data (List[Dict]): List of stock data
        ticker (str): Stock ticker symbol
        include_recommendations (bool): Include trading recommendations
        
    Returns:
        Dict[str, Any]: Comprehensive financial summary
    """
    try:
        if not stock_data or not isinstance(stock_data, list):
            return {
                "success": False,
                "message": "Invalid stock data provided",
                "data": None
            }
        
        # Use other analysis tools to get comprehensive data
        trend_analysis = analyze_stock_trends(stock_data, ticker)
        volatility_analysis = calculate_volatility_metrics(stock_data, ticker)
        
        if not trend_analysis["success"] or not volatility_analysis["success"]:
            return {
                "success": False,
                "message": "Failed to generate comprehensive analysis",
                "data": None
            }
        
        # Compile comprehensive summary
        summary = {
            "ticker": ticker,
            "report_date": datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            "data_period": trend_analysis["data"]["analysis_period"],
            "executive_summary": {
                "current_price": trend_analysis["data"]["price_metrics"]["current_price"],
                "trend_direction": trend_analysis["data"]["trend_analysis"]["direction"],
                "volatility_level": volatility_analysis["data"]["volatility_classification"],
                "overall_performance": trend_analysis["data"]["price_metrics"]["total_change_percent"]
            },
            "detailed_analysis": {
                "price_analysis": trend_analysis["data"]["price_metrics"],
                "volatility_analysis": volatility_analysis["data"]["basic_volatility"],
                "risk_metrics": volatility_analysis["data"]["risk_metrics"],
                "technical_levels": {
                    "support": trend_analysis["data"]["trend_analysis"]["support_level"],
                    "resistance": trend_analysis["data"]["trend_analysis"]["resistance_level"]
                }
            },
            "key_insights": trend_analysis["data"]["insights"] + volatility_analysis["data"]["insights"]
        }
        
        # Add recommendations if requested
        if include_recommendations:
            recommendations = []
            
            # Price-based recommendations
            price_change = trend_analysis["data"]["price_metrics"]["total_change_percent"]
            volatility = volatility_analysis["data"]["basic_volatility"]["annualized_volatility"]
            
            if price_change > 10 and volatility < 0.2:
                recommendations.append("Consider taking profits if holding long positions due to strong recent performance.")
            elif price_change < -10 and volatility < 0.25:
                recommendations.append("Potential buying opportunity if fundamentals remain strong.")
            elif volatility > 0.4:
                recommendations.append("Exercise caution due to high volatility - consider position sizing.")
            
            # Technical recommendations
            current_price = trend_analysis["data"]["price_metrics"]["current_price"]
            support = trend_analysis["data"]["trend_analysis"]["support_level"]
            resistance = trend_analysis["data"]["trend_analysis"]["resistance_level"]
            
            if current_price < support * 1.05:
                recommendations.append("Price near support level - watch for potential bounce.")
            elif current_price > resistance * 0.95:
                recommendations.append("Price near resistance level - potential profit-taking zone.")
            
            if not recommendations:
                recommendations.append("Hold current positions and monitor for technical breakouts.")
            
            summary["recommendations"] = recommendations
        
        # Generate narrative summary
        narrative = f"""
        Financial Summary for {ticker}:
        
        {ticker} is currently trading at ${summary['executive_summary']['current_price']:.2f}, showing a {summary['executive_summary']['trend_direction'].lower()} trend with {summary['executive_summary']['overall_performance']:+.2f}% performance over the analyzed period.
        
        The stock exhibits {summary['executive_summary']['volatility_level'].lower()} volatility, indicating {'stable' if summary['executive_summary']['volatility_level'] in ['Low', 'Very Low'] else 'elevated'} price movements.
        
        Technical analysis shows support at ${summary['detailed_analysis']['technical_levels']['support']:.2f} and resistance at ${summary['detailed_analysis']['technical_levels']['resistance']:.2f}.
        
        Risk metrics indicate a Sharpe ratio of {summary['detailed_analysis']['risk_metrics']['sharpe_ratio']:.2f}, suggesting {'good' if summary['detailed_analysis']['risk_metrics']['sharpe_ratio'] > 1 else 'poor' if summary['detailed_analysis']['risk_metrics']['sharpe_ratio'] < 0 else 'moderate'} risk-adjusted returns.
        """
        
        summary["narrative_summary"] = narrative.strip()
        
        return {
            "success": True,
            "message": f"Comprehensive financial summary generated for {ticker}",
            "data": summary
        }
        
    except Exception as e:
        return {
            "success": False,
            "message": f"Error generating financial summary: {str(e)}",
            "data": None
        }


def _calculate_max_drawdown(price_series):
    """Helper function to calculate maximum drawdown."""
    try:
        cumulative = (1 + price_series.pct_change()).cumprod()
        running_max = cumulative.expanding().max()
        drawdown = (cumulative - running_max) / running_max
        return drawdown.min()
    except:
        return None 