# Generated by NeuroStack
# Vendored from platform origin: tool/prime_number_tools (upstream_version=platform)


"""
Generated Tools - prime_number_tools.py

Auto-generated tools created by the Tool Generator.
Generated on: 2024-07-03 13:58:00
Total tools: 1
"""

from typing import Dict, Any, List

def calculate_primes(n: int) -> Dict[str, Any]:
    """
    Calculates the first N prime numbers.

    Args:
        n (int): The number of prime numbers to calculate.

    Returns:
        Dict[str, Any]: A dictionary containing the success status, message, and a list of the first N prime numbers.
                       Example: {"success": True, "message": "Successfully calculated the first 5 prime numbers.", "data": {"primes": [2, 3, 5, 7, 11]}}
    """
    try:
        if not isinstance(n, int) or n <= 0:
            return {
                "success": False,
                "message": "Invalid input. N must be a positive integer.",
                "data": {}
            }

        primes = []
        num = 2
        while len(primes) < n:
            is_prime = True
            for i in range(2, int(num**0.5) + 1):
                if num % i == 0:
                    is_prime = False
                    break
            if is_prime:
                primes.append(num)
            num += 1

        return {
            "success": True,
            "message": f"Successfully calculated the first {n} prime numbers.",
            "data": {"primes": primes}
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"An unexpected error occurred: {str(e)}",
            "data": {}
        }
